# Generated by Django 5.2.6 on 2025-09-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_report_is_resolved'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
