# Generated by Django 5.2.6 on 2025-09-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_comment_parent_alter_comment_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
