# Generated by Django 5.2.6 on 2025-09-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_project_needs_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('art', 'Art'), ('music', 'Music'), ('film', 'Film & Video'), ('design', 'Design'), ('food', 'Food'), ('publishing', 'Publishing'), ('games', 'Games'), ('fashion', 'Fashion'), ('health', 'Health & Fitness'), ('education', 'Education'), ('environment', 'Environment'), ('community', 'Community')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
